// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReversiMvcApp.Data.Context;

#nullable disable

namespace ReversiMvcApp.Data.Context.Migrations
{
    [DbContext(typeof(ReversiDbIdentityContext))]
    [Migration("20240627081907_AddAuditableFieldsToSpelerAndSpel")]
    partial class AddAuditableFieldsToSpelerAndSpel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "44f80e14-9ca1-48db-b6cc-2a3153d01657",
                            Name = "Mediator",
                            NormalizedName = "MEDIATOR"
                        },
                        new
                        {
                            Id = "512a1ac9-a17e-4602-a200-bf9e0ac10a6c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d4297ca9-77fe-496f-a148-7c7232811f85",
                            Name = "Speler",
                            NormalizedName = "SPELER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "60c35514-e6cf-47f4-84ad-8b010ce0b7b4",
                            RoleId = "512a1ac9-a17e-4602-a200-bf9e0ac10a6c"
                        },
                        new
                        {
                            UserId = "a5b07a52-c6e0-4dab-8a28-42c038e0cbb7",
                            RoleId = "44f80e14-9ca1-48db-b6cc-2a3153d01657"
                        },
                        new
                        {
                            UserId = "c7d9dd9f-99bc-422f-8f7f-0828c45acf68",
                            RoleId = "d4297ca9-77fe-496f-a148-7c7232811f85"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReversiMvcApp.Models.Spel", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AandeBeurt")
                        .HasColumnType("int");

                    b.Property<string>("Bord")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SpelIsAfgelopen")
                        .HasColumnType("bit")
                        .HasColumnName("Afgelopen");

                    b.HasKey("ID");

                    b.ToTable("Spellen");
                });

            modelBuilder.Entity("ReversiMvcApp.Models.Speler", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AantalGelijk")
                        .HasColumnType("int");

                    b.Property<int>("AantalGewonnen")
                        .HasColumnType("int");

                    b.Property<int>("AantalVerloren")
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Kleur")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("Spel");

                    b.HasIndex("SpelID");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "60c35514-e6cf-47f4-84ad-8b010ce0b7b4",
                            AantalGelijk = 0,
                            AantalGewonnen = 0,
                            AantalVerloren = 0,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2cf65307-59e0-4a98-8fca-d5b75f8ab0ed",
                            CreatedOn = new DateTime(2024, 6, 27, 8, 19, 6, 488, DateTimeKind.Utc).AddTicks(2324),
                            Email = "admin@reversi.nl",
                            EmailConfirmed = true,
                            IsEnabled = true,
                            Kleur = 0,
                            LastUpdated = new DateTime(2024, 6, 27, 8, 19, 6, 488, DateTimeKind.Utc).AddTicks(2327),
                            LockoutEnabled = false,
                            Naam = "Admin Bram",
                            NormalizedEmail = "ADMIN@REVERSI.NL",
                            NormalizedUserName = "ADMIN@REVERSI.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEKq4qN1FpxAAB7y/SFwHjMjSAKOmxwzddQAP3icZMvffDRL0oj7eZcXHJfdNlu4jEA==",
                            PhoneNumber = "12345678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1db604ad-61a4-4db9-ab99-31c7ce9d860c",
                            TwoFactorEnabled = false,
                            UserName = "admin@reversi.nl"
                        },
                        new
                        {
                            Id = "a5b07a52-c6e0-4dab-8a28-42c038e0cbb7",
                            AantalGelijk = 0,
                            AantalGewonnen = 0,
                            AantalVerloren = 0,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cd5c3e8d-c22c-4aee-8be9-273bc1ba9c34",
                            CreatedOn = new DateTime(2024, 6, 27, 8, 19, 6, 586, DateTimeKind.Utc).AddTicks(1517),
                            Email = "mediator@reversi.nl",
                            EmailConfirmed = true,
                            IsEnabled = true,
                            Kleur = 0,
                            LastUpdated = new DateTime(2024, 6, 27, 8, 19, 6, 586, DateTimeKind.Utc).AddTicks(1524),
                            LockoutEnabled = false,
                            Naam = "Mediator Bram",
                            NormalizedEmail = "MEDIATOR@REVERSI.NL",
                            NormalizedUserName = "MEDIATOR@REVERSI.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEN9RJ6QnIoLXMZ0KbZ8yOY3X71WgMaLzoCeKVoIC+802MYQ9Gpx1BEBA9l9FXIk7CQ==",
                            PhoneNumber = "12345678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ac83e299-0bb7-4dc1-a8b7-49077a6fc53d",
                            TwoFactorEnabled = false,
                            UserName = "mediator@reversi.nl"
                        },
                        new
                        {
                            Id = "c7d9dd9f-99bc-422f-8f7f-0828c45acf68",
                            AantalGelijk = 0,
                            AantalGewonnen = 0,
                            AantalVerloren = 0,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3b9cf5d5-098b-4e8e-b0d2-51feaa98261a",
                            CreatedOn = new DateTime(2024, 6, 27, 8, 19, 6, 672, DateTimeKind.Utc).AddTicks(3616),
                            Email = "speler@reversi.nl",
                            EmailConfirmed = true,
                            IsEnabled = true,
                            Kleur = 0,
                            LastUpdated = new DateTime(2024, 6, 27, 8, 19, 6, 672, DateTimeKind.Utc).AddTicks(3626),
                            LockoutEnabled = false,
                            Naam = "Bram",
                            NormalizedEmail = "SPELER@REVERSI.NL",
                            NormalizedUserName = "SPELER@REVERSI.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEA9Nf+nYAJsl0BuuHbMXgRJAnWsA6ZGdNMrAkcJd+Xa8UFLT/N97MM7E2YVTXy38OA==",
                            PhoneNumber = "12345678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a664cade-09b1-4502-8434-15c5f8b13b99",
                            TwoFactorEnabled = false,
                            UserName = "speler@reversi.nl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ReversiMvcApp.Models.Speler", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ReversiMvcApp.Models.Speler", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReversiMvcApp.Models.Speler", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ReversiMvcApp.Models.Speler", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReversiMvcApp.Models.Speler", b =>
                {
                    b.HasOne("ReversiMvcApp.Models.Spel", "ActueelSpel")
                        .WithMany()
                        .HasForeignKey("Spel");

                    b.HasOne("ReversiMvcApp.Models.Spel", null)
                        .WithMany("Spelers")
                        .HasForeignKey("SpelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ActueelSpel");
                });

            modelBuilder.Entity("ReversiMvcApp.Models.Spel", b =>
                {
                    b.Navigation("Spelers");
                });
#pragma warning restore 612, 618
        }
    }
}
